FROM node:22-alpine

WORKDIR /app

# Install build dependencies
RUN apk update && apk add --no-cache \
    g++ \
    python3 \
    py3-pip \
    openjdk17-jdk \
    bash \
    && ln -sf python3 /usr/bin/python \
    && ln -sf pip3 /usr/bin/pip

# Set Java environment
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk
ENV PATH="$JAVA_HOME/bin:${PATH}"

COPY . .
RUN npm install


EXPOSE 5001

CMD ["node", "server.js"]
